#!/bin/sh
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_102.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_129.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_131.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_134.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_135.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_13.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_143.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_14.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_153.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_169.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_172.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_177.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_187.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_197.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_199.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_205.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_207.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_209.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_213.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_220.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_223.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_22.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_230.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_232.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_234.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_241.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_243.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_24.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_257.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_263.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_27.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_281.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_285.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_28.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_30.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_39.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_42.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_47.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_52.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_53.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_58.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_60.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_76.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_81.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_88.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_89.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_91.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_93.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_94.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_A_99.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_100.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_108.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_118.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_129.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_130.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_136.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_137.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_146.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_149.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_14.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_152.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_161.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_167.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_169.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_16.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_171.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_17.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_181.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_192.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_193.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_202.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_204.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_207.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_209.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_217.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_219.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_225.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_228.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_239.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_244.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_258.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_264.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_265.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_285.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_287.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_289.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_291.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_40.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_44.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_56.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_57.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_58.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_59.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_66.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_6.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_78.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_81.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_94.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_95.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_B_9.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_105.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_125.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_12.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_134.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_136.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_144.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_145.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_14.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_151.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_157.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_163.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_165.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_174.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_175.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_180.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_182.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_198.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_200.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_217.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_21.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_224.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_227.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_233.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_234.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_235.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_242.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_246.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_24.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_263.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_270.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_275.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_276.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_278.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_289.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_297.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_299.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_39.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_41.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_45.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_48.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_51.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_59.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_65.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_72.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_74.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_75.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_81.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_83.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_84.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C1_85.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_118.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_119.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_120.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_121.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_127.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_129.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_134.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_13.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_144.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_154.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_161.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_166.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_169.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_173.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_179.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_183.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_187.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_204.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_205.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_213.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_216.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_231.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_234.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_244.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_245.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_246.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_251.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_259.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_260.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_264.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_271.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_279.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_280.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_282.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_284.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_285.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_287.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_289.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_295.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_2.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_34.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_45.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_51.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_60.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_68.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_78.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_89.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_92.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_94.txt
cat /home/kyunghwan/upper_angle/upper_img_angle/B_240_C2_98.txt